version: '3'

services:
  # Your existing FastAPI app
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
    networks:
      - app-network

  # Streamlit UI
  streamlit:
    image: python:3.11.9
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    command: bash -c "pip install streamlit requests && streamlit run /app/frontend/streamlit_app.py --server.port=8501 --server.address=0.0.0.0"
    depends_on:
      - api
    networks:
      - app-network

  # MLflow tracking server
  mlflow:
    image: python:3.11.9
    working_dir: /mlflow
    volumes:
      - ./mlruns:/mlflow/mlruns
    ports:
      - "5001:5000"
    command: bash -c "pip install mlflow && mlflow server --host 0.0.0.0 --port 5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge